services:
  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - backup:/backup
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
    networks:
      main:
        aliases:
          - db

  zope:
    image: python:${PYTHON_VERSION}
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    build:
      dockerfile: zope-Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    environment:
        ZOPE_VERSION: ${ZOPE_VERSION}
        ZOPE_ROOT_PASSWORD: ${ZOPE_ROOT_PASSWORD}
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - zope-data:/usr/local/share/ihs
      - zope-filestorage:/usr/local/share/ihs/var/filestorage
      - backup:/backup
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.01:8080"]
    networks:
      main:
        aliases:
          - zope
  
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    restart: always
    ports:
      - 127.0.0.1:8088:8088
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: https://${NGINX_HOST}/mysql/
      UPLOAD_LIMIT: 1G
      APACHE_PORT: 8088
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "service", "apache2", "status"]
    networks:
      main:
        aliases:
          - phpmyadmin

  web:
    image: nginx:${NGINX_VERSION}
    restart: always
    build:
      dockerfile: nginx-Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGINX_HOST: ${NGINX_HOST}
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_ALLOW=${NGINX_ALLOW}
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ./ssl:/etc/ssl/nginx
    depends_on:
      - zope
      - phpmyadmin
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    networks:
      main:
        aliases:
          - web

volumes:
  mariadb-data:
  zope-data:
  zope-filestorage:
  backup:

networks:
  main:
