services:
  db:
    image: mariadb:11.2
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
    command: [
      "--wait_timeout=31536000",
      "--interactive_timeout=31536000"
    ]
    networks:
      main:
        aliases:
          - db

  zope:
    image: svenkleinert/pxd-ihs-zope:13.0.0
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
        ZOPE_ROOT_PASSWORD: ${ZOPE_ROOT_PASSWORD}
    volumes:
      - zope-data:/usr/local/share/ihs/ihs-instances
      - zope-import:/usr/local/share/ihs/var/zopeinstance/import
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.01:8080"]
    networks:
      main:
        aliases:
          - zope
  
  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 127.0.0.1:8088:8088
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: https://${NGINX_HOST}/mysql/
      UPLOAD_LIMIT: 1G
      APACHE_PORT: 8088
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "service", "apache2", "status"]
    networks:
      main:
        aliases:
          - phpmyadmin

  web:
    image: svenkleinert/pxd-ihs-nginx:1.25
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_ALLOW=${NGINX_ALLOW}
    volumes:
      - ./ssl:/etc/ssl/nginx
    depends_on:
      - zope
      - phpmyadmin
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    networks:
      main:
        aliases:
          - web

volumes:
  mariadb-data:
  zope-data:
  zope-import:

networks:
  main:
